### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Lootgoblin01** [SinsOfSeven/TexFx#11]
Everytime i open the game if i try to load Bennet, Kuki Shinobu, Xiangling, Kachina or Mualani the game crashes.
I even try to load only the this mod and reinstalling a fresh 3Dmigoto with only this mod but it doesn't work.
I use a radeon 6900xt and a ryzen 7 5800x 3D

**Comment by ozzycvc** [comment]
I can report that I have the exact same issue. I have an AMD system also. I downgraded the version to 1.046 and now I dont get the crashes anymore.

**Comment by SinsOfSeven** [comment]
This issue should be fixed as of 1.051, you experience any other crashes please report them.
