### ISSUE TITLE
The "outline" of Furina and Xianyun characters has an error and is not displaying the correct color. 

### ISSUE THREAD

**Issue by chivoha** [SinsOfSeven/TexFx#14]
The "outline" of Furina and Xianyun characters has an error and is not displaying the correct color (Xilonen also has problems). I have installed the latest "ORFIX" Version 0.2.91, "TeFx version" 1.051.
![Ảnh chụp màn hình (38)](https://github.com/user-attachments/assets/4f77970b-e856-4797-8f55-38f2b55d1d2c)
![Ảnh chụp màn hình (39)](https://github.com/user-attachments/assets/9a4314f3-fa23-49f1-8502-6bca96129424)
![Ảnh chụp màn hình (40)](https://github.com/user-attachments/assets/3c09f1ea-71a3-4b9a-a516-3ba35bd96bdb)
TeFx 1.046 does not have this problem.
![Ảnh chụp màn hình (41)](https://github.com/user-attachments/assets/323acd9b-6049-4c8f-8350-3ac27f87d8a8)
![Ảnh chụp màn hình (42)](https://github.com/user-attachments/assets/99174e1f-b8cb-45e2-81da-8c844f9d37ed)
![Ảnh chụp màn hình (43)](https://github.com/user-attachments/assets/f6d2f58d-ba0b-4618-86f3-4eafba563888)

**Comment by SinsOfSeven** [comment]
Most likely, you need to update ORFix, or ORFix needs to be updated. In 1.046, I had a line which "fixed" some ORFix mods, but broke others so I removed it. This is NOT a texfx issue, which is why the change was removed.
