### ISSUE TITLE
Transparency wrong under Sunlight and Crash underwater.

### ISSUE THREAD

**Issue by DiamondPugs** [SinsOfSeven/TexFx#4]
The latest update breaks the transparency effect under direct sun light and crashes underwater (Seems to get really bright before crashing).

GPU: AMD 4Gb RX 470

**Comment by SinsOfSeven** [comment]
Heya, I'm pushing an update to fix the underwater crashes right now, but I'd need more information about the sunlight thing. 
let me know if it persists after the fix for underwater. Update is `1.041` which is already pushed, but I am updating the releases on GB and here as a hotfix.

**Comment by DiamondPugs** [comment]
I just tested it and I'm still having both issues. Crashing underwater and weird transparency under the sun. I'm adding a screenshot so you can see what the issue looks like.
![TexFXBug](https://github.com/SinsOfSeven/TexFx/assets/164430055/b38432a3-52c6-4421-b799-03a5087d8b5d)

**Comment by TerminalAide0017** [comment]
Thanks for the update, 1.043 (the current source code) should definitely fix the water:tm: I've had 2 people verify it works the same as 1.035.

Unfortunately I don't really know what is causing the 2nd issue. It reminds me of something I've seen, and it could be related to the underlying texture. But I really couldn't say the exact cause currently. It is difficult to reproduce some of these issues on my end.

**Comment by DiamondPugs** [comment]
I can confirm the underwater crash is fixed.

As for the transparency issue, it seems to have improved, and from my testing it looks like it isn't the transparency itself, but how the game renders the shadows on some alpha textures with the new version.

I'll mark the issue as closed.
